<?php

function titlecase_menu() {
    $items = array();
    $items['titlecase'] = array(
        'title' => 'Title Case Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('titlecase_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_success'] = array(
        'title' => 'Success',
        'page callback' => 'titlecase_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function titlecase_form() {
    $form['input'] = array(
        '#title' => 'Enter in a title to convert',
        '#type' => 'textfield',
        '#description' => t('Please enter your title'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Make Title Case',
    );
    return $form;
}

function make_title_case($input){
    strtolower($input);
    $generate = ucfirst($input);
    return $generate;
}

function titlecase_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];
    $result = make_title_case($input);
    $_SESSION['title'] = $result;

    $form_state['redirect'] = 'title_success';
}

function titlecase_success() {
    $title = $_SESSION['title'];
    return '<p>Your titlecased string: ' . $title . '</p>';
}
